
runs_dir: output/31_real_campus_5

example_name: real_campus_5

seed: -1
frames: 10

finetune_decoder_gen: True
finetune_decoder_interp: True
finetune_depth_model: True

num_scenes: 4
num_keyframes: 2
use_gpt: True
kf2_upsample_coef: 4
skip_interp: False
skip_gen: False
enable_regenerate: True

debug: True
inpainting_resolution_gen: 512

rotation_range: 0.45
rotation_path: [0, 0, 0, 1, 1, 0, 0, 0]
camera_speed_multiplier_rotation: 0.2
save_fps: 10
